### ISSUE TITLE
The app does not display snippets

### ISSUE THREAD

**Issue by VG08** [Abdesol/CutCode#2]
[

https://user-images.githubusercontent.com/71305756/128990820-a24ca8f3-9c04-4615-a596-13cd728f6071.mp4

](url)
When I go to home and change some filters, even though it should display snippets it doesn't I have attached a video in which this happens

**Comment by VG08** [comment]
The snips start appearing again when I click the cross in the search bar

**Comment by Abdesol** [comment]
I am very thankful to you for reporting this bug. 
I will try to fix this and release the next version in a minimum time possible.
The bug above shows that when you come back to All languages, it is not showing all of them.

**Comment by VG08** [comment]
Not only is it not showing all languages, when I go in python it doesn't show

**Comment by VG08** [comment]
Also a bit off this issue, shouldn't the releases tab have the installer of the app instead of the source code

**Comment by Abdesol** [comment]
ohok will manage to fix that too.

**Comment by Abdesol** [comment]
Well, I am done with the above issue you listed and some other issues I found myself.
Here is the V1.1 release https://github.com/Abdesol/CutCode/releases/tag/V1.1
And let me know if there are any other issues.
Have a good time :)
